# Template maven-build

# This template allows you to test and build your Java project with Maven.
# The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.8.7

pipelines:
  default:
    - parallel:
      - step:
          name: Clean
          caches:
            - maven
          script:
            - mvn clean
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
            - mvn serenity:aggregate
            # Copy the Serenity report files to the target folder
            - cp target/site/serenity/* target/site/ -r
            - mv target/site/serenity/index.html target/site/
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1